// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CompanySelectionController from "./company_selection_controller"
application.register("company-selection", CompanySelectionController)

import DarkModeController from "./dark_mode_controller"
application.register("dark-mode", DarkModeController)

import FlashMessageController from "./flash_message_controller"
application.register("flash-message", FlashMessageController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
