# .rubocop.yml

AllCops:
  NewCops: enable
  Exclude:
    - "bin/bundle"
    - "config/environments/**/*"
    - "vendor/bundle/**/*"

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120
