name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.0"
          bundler-cache: true

      - name: Install Yarn
        run: |
          curl -o- -L https://yarnpkg.com/install.sh | bash
          export PATH="$HOME/.yarn/bin:$PATH"

      - name: Install Node.js dependencies
        run: |
          yarn install

      - name: Install dependencies
        run: |
          sudo apt-get -yqq install libpq-dev
          bundle install

      - name: Precompile assets
        env:
          RAILS_ENV: test
        run: |
          bundle exec rake assets:precompile

      - name: Run RuboCop
        run: |
          bundle exec rubocop

      - name: Run Slim-Lint
        run: |
          bundle exec slim-lint .

      - name: Set up the database
        env:
          RAILS_ENV: test
        run: |
          cp config/database.yml.ci config/database.yml
          bundle exec rake db:create
          bundle exec rake db:schema:load

      - name: Run tests
        env:
          RAILS_ENV: test
        run: |
          bundle exec rspec ./spec
